# -*- coding: utf-8 -*-
"""Copia di ANALISI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pp5cR1qYHNX62ei81o7hEdkSlfIB54st
"""

import pandas as pd
import numpy as np
import io
from google.colab import files
import matplotlib.pyplot as plt

upl = files.upload()

file_rd = pd.read_csv( io.BytesIO( upl['888 - Foglio1.csv'] ) )
file_dt = pd.DataFrame( file_rd )
file_dt

def ANALISI( label ):
    print("Running "+label+"...")
    file_atp = file_dt.loc[ ( file_dt.TIPO==label ) ]
    #file_atp
    qt = list( file_atp['QUOTA'] )
    scms = list( file_atp['SCOMMESSA'] )

    quote = []
    for q in qt:
      q = q.replace(",", ".")
      q = float( q )
      quote.append( q )

    scommesse = []
    for s in scms:
      s = s.replace(",", ".")
      s = s.replace("€", "")
      s = s.strip()
      s = float( s )
      scommesse.append( s )

    profitto_atp = list( file_atp.PROFITTO )
    profitto_atp_ord = []
    segni = []
    for idx, v in enumerate ( profitto_atp ):
        v = v.replace("€", "")
        v = v.strip()
        v = v.replace(',', '.')
        if "-" in v:
            segni.append( -1 )
        else:
            segni.append( 1 )
        v = v.replace('-','')
        v = v.strip()
        v = float( v )
        profitto_atp_ord.append( v )

    print( profitto_atp_ord )
    print( segni )

    lista_finale_atp = []
    for ind, val in enumerate ( profitto_atp_ord ):
        prd = val*segni[ind]
        lista_finale_atp.append( prd )
    numero_scommesse = len( lista_finale_atp )
    print( lista_finale_atp )
    somma_atp = sum( lista_finale_atp )
    somma_atp = round(somma_atp,2) 
    media_profitto = somma_atp/(numero_scommesse+0.000005)
    conto_win = 0
    for lfatp in lista_finale_atp:
      if lfatp>0:
        conto_win = conto_win+1
      else:
        conto_win = conto_win+0
    win_percentage = (conto_win/(numero_scommesse+0.00005) )*100

    win_under_1_5 = 0
    tot_under_1_5 = 0

    win_1_5_2 = 0
    tot_1_5_2 = 0

    win_over_2 = 0
    tot_over_2 = 0
    
    for idx, sc in enumerate ( lista_finale_atp ):
      if quote[idx]<=1.5:
        tot_under_1_5 = tot_under_1_5+1
        if sc>0:
          win_under_1_5 = win_under_1_5+1
      elif ( quote[idx]>1.5 )&( quote[idx]<=2 ):
        tot_1_5_2 = tot_1_5_2+1
        if sc>0:
          win_1_5_2 = win_1_5_2+1
      else:
        tot_over_2 = tot_over_2+1
        if sc>0:
          win_over_2 = win_over_2+1





    print("Profitto totale: ", str( somma_atp ) )
    print("Profitto medio: ", str( media_profitto )," su ", str(numero_scommesse)," scommesse" )
    print("Percentuale di vittoria:", str( win_percentage ) )

    print("Analisi dettagliata: \n")
    print(str( win_under_1_5 ), " scommesse prese su ", str( tot_under_1_5 ), " con quota inferiore o uguale a 1.5" )
    print(str( win_1_5_2 ), " scommesse prese su ", str( tot_1_5_2 ), " con quota tra 1.51 e 2" )
    print(str( win_over_2 ), " scommesse prese su ", str( tot_over_2 ), " con quota superiore a 2 \n" )
    
    print("Il GRAFICO A DISPERSIONE SOTTOSTANTE serve per valutare la correlazione tra il profitto e la quota.")
    plt.scatter( quote, lista_finale_atp )
    plt.xlabel("QUOTA")
    plt.ylabel("PROFITTO")
    plt.show()

    print("Il GRAFICO A DISPERSIONE SOTTOSTANTE serve per valutare la correlazione tra il profitto e la puntata.")
    plt.scatter( scommesse, lista_finale_atp )
    plt.xlabel("PUNTATA")
    plt.ylabel("PROFITTO")
    plt.show()


    
    print("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ")

types_bet = list( file_dt['TIPO'].unique() )

for v in types_bet:
    if type(v)==float:
        types_bet.remove(v)
    else:
        pass
print( types_bet )

for tb in types_bet:
    ANALISI(tb)

def ANALISI_day( label, data_int ):
    print("Running "+label+"...")
    file_atp = file_dt.loc[ ( file_dt.TIPO==label )&( file_dt.GIORNO==data_int) ]
    #file_atp
    qt = list( file_atp['QUOTA'] )
    scms = list( file_atp['SCOMMESSA'] )

    quote = []
    for q in qt:
      q = q.replace(",", ".")
      q = float( q )
      quote.append( q )

    scommesse = []
    for s in scms:
      s = s.replace(",", ".")
      s = s.replace("€", "")
      s = s.strip()
      s = float( s )
      scommesse.append( s )

    profitto_atp = list( file_atp.PROFITTO )
    profitto_atp_ord = []
    segni = []
    for idx, v in enumerate ( profitto_atp ):
        v = v.replace("€", "")
        v = v.strip()
        v = v.replace(',', '.')
        if "-" in v:
            segni.append( -1 )
        else:
            segni.append( 1 )
        v = v.replace('-','')
        v = v.strip()
        v = float( v )
        profitto_atp_ord.append( v )

    print( profitto_atp_ord )
    print( segni )

    lista_finale_atp = []
    for ind, val in enumerate ( profitto_atp_ord ):
        prd = val*segni[ind]
        lista_finale_atp.append( prd )
    numero_scommesse = len( lista_finale_atp )
    print( lista_finale_atp )
    somma_atp = sum( lista_finale_atp )
    somma_atp = round(somma_atp,2) 
    media_profitto = somma_atp/(numero_scommesse+0.000005)
    conto_win = 0
    for lfatp in lista_finale_atp:
      if lfatp>0:
        conto_win = conto_win+1
      else:
        conto_win = conto_win+0
    win_percentage = (conto_win/( numero_scommesse+0.00005) )*100

    win_under_1_5 = 0
    tot_under_1_5 = 0

    win_1_5_2 = 0
    tot_1_5_2 = 0

    win_over_2 = 0
    tot_over_2 = 0
    
    for idx, sc in enumerate ( lista_finale_atp ):
      if quote[idx]<=1.5:
        tot_under_1_5 = tot_under_1_5+1
        if sc>0:
          win_under_1_5 = win_under_1_5+1
      elif ( quote[idx]>1.5 )&( quote[idx]<=2 ):
        tot_1_5_2 = tot_1_5_2+1
        if sc>0:
          win_1_5_2 = win_1_5_2+1
      else:
        tot_over_2 = tot_over_2+1
        if sc>0:
          win_over_2 = win_over_2+1





    print("Profitto totale: ", str( somma_atp ) )
    print("Profitto medio: ", str( media_profitto )," su ", str(numero_scommesse)," scommesse" )
    print("Percentuale di vittoria:", str( win_percentage ) )

    print("Analisi dettagliata: \n")
    print(str( win_under_1_5 ), " scommesse prese su ", str( tot_under_1_5 ), " con quota inferiore o uguale a 1.5" )
    print(str( win_1_5_2 ), " scommesse prese su ", str( tot_1_5_2 ), " con quota tra 1.51 e 2" )
    print(str( win_over_2 ), " scommesse prese su ", str( tot_over_2 ), " con quota superiore a 2 \n" )
    
    print("Il GRAFICO A DISPERSIONE SOTTOSTANTE serve per valutare la correlazione tra il profitto e la quota.")
    plt.scatter( quote, lista_finale_atp )
    plt.xlabel("QUOTA")
    plt.ylabel("PROFITTO")
    plt.show()

    print("Il GRAFICO A DISPERSIONE SOTTOSTANTE serve per valutare la correlazione tra il profitto e la puntata.")
    plt.scatter( scommesse, lista_finale_atp )
    plt.xlabel("PUNTATA")
    plt.ylabel("PROFITTO")
    plt.show()


    
    print("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ")

for tb in types_bet:
    ANALISI_day(tb, "9 genn")

